config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: %i[index new create]
  end
  resources :reviews, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, allow_blank: false,
                       inclusion: {
                         in: %w[chinese italian japanese french belgian],
                         message: 'Sorry, it is not a valid category'
                       }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant, presence: true, allow_nil: false
  validates :content, presence: true, allow_blank: false
  validates :rating, presence: true, allow_blank: false,
                     numericality: { only_integer: true },
                     inclusion: { in: (0..5).to_a }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant)
          .permit(:name, :phone_number, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show]
  before_action :set_restaurant
  def index
  end

  def show
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save!
    redirect_to restaurant_path(@restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container w-50 border" style="margin-top: 48px">
  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name, label: 'Restaurant name', error: 'Name is required' %>
    <%= f.input :address, label: 'Full address', error: 'Address is required'  %>
    <%= f.input :category, label: 'Category', error: 'Category is required' %>
    <%= f.input :phone_number, label: 'Phone'%>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<div class="d-flex justify-content-between" style="margin-top: 16px">
  <h1>All the restaurants</h1>
  <%= link_to "Add a restaurant", new_restaurant_path %>
</div>
<hr>
<div class="container">
  <table style="border-collapse: separate; border-spacing: 16px;">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Category</th>
        <th>Phone number</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @restaurants.each do |resto| %>
      <tr>
        <td><%= resto.id %></td>
        <td><%= resto.name %></td>
        <td><%= resto.address %></td>
        <td><%= resto.category %></td>
        <td><%= resto.phone_number %></td>
        <td><%= link_to "See details", restaurant_path(resto) %></td>
      </tr>
    <%end%>
    </tbody>
  </table>
</div>
<hr>

app/views/restaurants/new.html.erb
<div class="container text-center" style="margin-top: 16px">
  <h1 class="text-center">Add a restaurant</h1>
</div>
<hr>
<div class="container text-center" style="margin-top: 16px">
  <div class="text-left">
    <%= render 'form', restaurant: @restaurant %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="d-flex justify-content-between w-5" style="margin-top: 16px">
  <div class="container text-left">
    <%= link_to "Back to home", restaurants_path %>
  </div>
  <div class="container text-right">
    <%= link_to "Add a review", new_restaurant_review_path(@restaurant)%>
  </div>
</div>
<hr>
<div class="d-flex">
  <div class="container">
    <h1><%= @restaurant.name %></h1>
    <p>Full address: <%= @restaurant.address %></p>
    <p>Category: <%= @restaurant.category %></p>
    <p>Phone: <%= @restaurant.phone_number || 'not given' %></p>
  </div>
  <div class="container">
    <h1>List of reviews</h1>
    <table style="border-collapse: separate; border-spacing: 16px;">
      <thead>
        <th>ID</th>
        <th>Review</th>
        <th>Rating</th>
      </thead>
      <tbody>
      <% @reviews.each do |rev|%>
        <tr>
          <td><%= rev.id %></td>
          <td><%= rev.content %></td>
          <td><%= rev.rating %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<hr>

app/views/reviews/_form.html.erb
<div class="container w-50 border" style="margin-top: 48px">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content, label: 'Review', error: 'Review is required' %>
    <%= f.input :rating, label: 'Rating', input_html: { min: '0', max:'5'}  %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container text-center" style="margin-top: 16px">
  <h1 class="text-center">Add a review</h1>
</div>
<hr>
<div class="container text-center" style="margin-top: 16px">
  <div class="text-left">
    <%= render 'form', restaurant: @restaurant, review: @review %>
  </div>
</div>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>